/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ApiPublicMemeImageIdRouteImport } from './routes/api/public/meme-image/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMemeImageIdRoute = ApiPublicMemeImageIdRouteImport.update({
  id: '/api/public/meme-image/$id',
  path: '/api/public/meme-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/api/public/meme-image/$id': typeof ApiPublicMemeImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/api/public/meme-image/$id': typeof ApiPublicMemeImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/api/public/meme-image/$id': typeof ApiPublicMemeImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/matches' | '/profile' | '/saved' | '/api/public/meme-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matches' | '/profile' | '/saved' | '/api/public/meme-image/$id'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/profile'
    | '/saved'
    | '/api/public/meme-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ApiPublicMemeImageIdRoute: typeof ApiPublicMemeImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meme-image/$id': {
      id: '/api/public/meme-image/$id'
      path: '/api/public/meme-image/$id'
      fullPath: '/api/public/meme-image/$id'
      preLoaderRoute: typeof ApiPublicMemeImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ApiPublicMemeImageIdRoute: ApiPublicMemeImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
