/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ApiSwipesRouteImport } from './routes/api/swipes'
import { Route as ApiMemesRandomRouteImport } from './routes/api/memes/random'
import { Route as ApiMemesSaveRouteImport } from './routes/api/memes/save'
import { Route as ApiMemesSavedRouteImport } from './routes/api/memes/saved'
import { Route as ApiUsersMatchesRouteImport } from './routes/api/users/matches'
import { Route as ApiUsersStatisticsRouteImport } from './routes/api/users/statistics'
import { Route as ApiPublicMemeImageIdRouteImport } from './routes/api/public/meme-image/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwipesRoute = ApiSwipesRouteImport.update({
  id: '/api/swipes',
  path: '/api/swipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemesRandomRoute = ApiMemesRandomRouteImport.update({
  id: '/api/memes/random',
  path: '/api/memes/random',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemesSaveRoute = ApiMemesSaveRouteImport.update({
  id: '/api/memes/save',
  path: '/api/memes/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemesSavedRoute = ApiMemesSavedRouteImport.update({
  id: '/api/memes/saved',
  path: '/api/memes/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMatchesRoute = ApiUsersMatchesRouteImport.update({
  id: '/api/users/matches',
  path: '/api/users/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersStatisticsRoute = ApiUsersStatisticsRouteImport.update({
  id: '/api/users/statistics',
  path: '/api/users/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMemeImageIdRoute = ApiPublicMemeImageIdRouteImport.update({
  id: '/api/public/meme-image/$id',
  path: '/api/public/meme-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/api/swipes': typeof ApiSwipesRoute
  '/api/memes/random': typeof ApiMemesRandomRoute
  '/api/memes/save': typeof ApiMemesSaveRoute
  '/api/memes/saved': typeof ApiMemesSavedRoute
  '/api/users/matches': typeof ApiUsersMatchesRoute
  '/api/users/statistics': typeof ApiUsersStatisticsRoute
  '/api/public/meme-image/$id': typeof ApiPublicMemeImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/api/swipes': typeof ApiSwipesRoute
  '/api/memes/random': typeof ApiMemesRandomRoute
  '/api/memes/save': typeof ApiMemesSaveRoute
  '/api/memes/saved': typeof ApiMemesSavedRoute
  '/api/users/matches': typeof ApiUsersMatchesRoute
  '/api/users/statistics': typeof ApiUsersStatisticsRoute
  '/api/public/meme-image/$id': typeof ApiPublicMemeImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/api/swipes': typeof ApiSwipesRoute
  '/api/memes/random': typeof ApiMemesRandomRoute
  '/api/memes/save': typeof ApiMemesSaveRoute
  '/api/memes/saved': typeof ApiMemesSavedRoute
  '/api/users/matches': typeof ApiUsersMatchesRoute
  '/api/users/statistics': typeof ApiUsersStatisticsRoute
  '/api/public/meme-image/$id': typeof ApiPublicMemeImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/profile'
    | '/saved'
    | '/api/swipes'
    | '/api/memes/random'
    | '/api/memes/save'
    | '/api/memes/saved'
    | '/api/users/matches'
    | '/api/users/statistics'
    | '/api/public/meme-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/profile'
    | '/saved'
    | '/api/swipes'
    | '/api/memes/random'
    | '/api/memes/save'
    | '/api/memes/saved'
    | '/api/users/matches'
    | '/api/users/statistics'
    | '/api/public/meme-image/$id'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/profile'
    | '/saved'
    | '/api/swipes'
    | '/api/memes/random'
    | '/api/memes/save'
    | '/api/memes/saved'
    | '/api/users/matches'
    | '/api/users/statistics'
    | '/api/public/meme-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ApiSwipesRoute: typeof ApiSwipesRoute
  ApiMemesRandomRoute: typeof ApiMemesRandomRoute
  ApiMemesSaveRoute: typeof ApiMemesSaveRoute
  ApiMemesSavedRoute: typeof ApiMemesSavedRoute
  ApiUsersMatchesRoute: typeof ApiUsersMatchesRoute
  ApiUsersStatisticsRoute: typeof ApiUsersStatisticsRoute
  ApiPublicMemeImageIdRoute: typeof ApiPublicMemeImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swipes': {
      id: '/api/swipes'
      path: '/api/swipes'
      fullPath: '/api/swipes'
      preLoaderRoute: typeof ApiSwipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memes/random': {
      id: '/api/memes/random'
      path: '/api/memes/random'
      fullPath: '/api/memes/random'
      preLoaderRoute: typeof ApiMemesRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memes/save': {
      id: '/api/memes/save'
      path: '/api/memes/save'
      fullPath: '/api/memes/save'
      preLoaderRoute: typeof ApiMemesSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memes/saved': {
      id: '/api/memes/saved'
      path: '/api/memes/saved'
      fullPath: '/api/memes/saved'
      preLoaderRoute: typeof ApiMemesSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/matches': {
      id: '/api/users/matches'
      path: '/api/users/matches'
      fullPath: '/api/users/matches'
      preLoaderRoute: typeof ApiUsersMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/statistics': {
      id: '/api/users/statistics'
      path: '/api/users/statistics'
      fullPath: '/api/users/statistics'
      preLoaderRoute: typeof ApiUsersStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meme-image/$id': {
      id: '/api/public/meme-image/$id'
      path: '/api/public/meme-image/$id'
      fullPath: '/api/public/meme-image/$id'
      preLoaderRoute: typeof ApiPublicMemeImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ApiSwipesRoute: ApiSwipesRoute,
  ApiMemesRandomRoute: ApiMemesRandomRoute,
  ApiMemesSaveRoute: ApiMemesSaveRoute,
  ApiMemesSavedRoute: ApiMemesSavedRoute,
  ApiUsersMatchesRoute: ApiUsersMatchesRoute,
  ApiUsersStatisticsRoute: ApiUsersStatisticsRoute,
  ApiPublicMemeImageIdRoute: ApiPublicMemeImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
